unify acquireFrame failure logic
Nvidia's original code locks the buffer queue before stopping, which
can be assumed is for good reason. Unfortunately it does not address:
Error: `STOPPING:because:"err" returned code:8` #14